services:
  redis:
    image: redis:8
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: 3G
    container_name: redis-server
    hostname: redis-server
    restart: always
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass redispassword"
    volumes:
      - ./rds_data:/data":rw
      - ./config:/usr/local/etc/redis:ro
    ports:
      - "6379:6379"

    networks:
      - kntgraph_net

  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=redis-server:6379
  #     - REDIS_PASSWORD=redispassword
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - fmh_net

networks:
  kntgraph_net:
    name: kntgraph_net
    external: true
