# SPDX-FileCopyrightText: 2026 kinetgraph
#
# SPDX-License-Identifier: Apache-2.0

"""
System — a pure function from World to list[Event].

In FMH v2.2, every system is the same shape:

    System: (World, new_events?) -> list[Event]

The framework invokes each registered system once per tick
(after the incremental World fold for reactive systems, after
the schedule tick for cyclic systems). Systems do NOT receive
the triggering event via the World (the World already
captures its effect via the projection); however, the
dispatcher may pass ``new_events`` as a keyword-only argument
for systems that need to process the events that were just
folded in this tick (e.g., a state machine cascading across
multiple events — see ADR-071 §3.4.2 and ADR-074 §5).

Two dispatchers drive ticks:

  - ``ReactiveDispatcher``: tick when the EventLog has new events
    for a tracked agent. Folds incrementally using
    ``World.with_event``.
  - ``Runner``: tick on a schedule (every N seconds). Builds a
    fresh World via ``fold_world``.

Both fold into the same World and call the same systems. The
distinction is purely about cadence, not signature.

The events passed via ``new_events`` are the ones the dispatcher
read from the EventLog this tick — they are already persisted
(the framework's invariant: an event is only valid after it
appears in the log). Events generated BY systems in this tick
are NOT in ``new_events``; they are appended to the log AFTER
the system returns and become visible in the next tick.

Backwards compat
----------------

The aliases ``ReactiveSystem`` and ``CyclicSystem`` are kept
for legacy imports. They share the same signature
(``(World, new_events=None) -> list[Event]``). Systems written
against the v2.0/2.1 ``ReactiveSystem(world, event)`` signature will
break at runtime — they need to drop the event parameter
and use ``world.query_agents(...)`` instead. See ADR-018.

See: ADR-018 — WorldIncremental + WorldSystem.

Properties of every system:

  - deterministic (same world + same system = same output)
  - testable in isolation (construct an in-memory world, call system)
  - replayable (re-running a system on the same world is a no-op)
  - composable (dispatcher pipelines any list of systems)
"""

from __future__ import annotations

import typing

if typing.TYPE_CHECKING:
    from .event import Event
    from .world import World

SystemReturn = typing.Union[list["Event"], typing.Awaitable[list["Event"]]]


@typing.runtime_checkable
class WorldSystem(typing.Protocol):
    """
    A pure function from World to list[Event].

    The framework invokes each registered system once per
    tick (after the incremental World fold). Systems inspect
    the World's components via ``world.query_agents(...)``
    and emit events based on the rules they encode.

    Discipline
    ----------

    The framework's source-of-truth model is:

      - **EventLog (Redis)**: append-only fact store.
      - **World**: deterministic projection of the EventLog
        onto the agent's current state, folded at the start
        of every tick.
      - **System**: pure function ``World -> list[Event]``
        that runs once per tick AFTER the fold.

    Because the World is folded BEFORE the systems run,
    every system already sees the full effect of the
    events from the current tick. The cursor
    (``view.cursors[<system_name>]``) and the
    ``view.last_event_id`` together identify what is new
    since the last tick; that is the ONLY "what changed"
    signal a system should consult.

    A system MUST NOT receive the raw event batch from
    the dispatcher's tick loop. The contract is precisely
    ``(world: World) -> list[Event]``. New events are
    always observable through the World (the projection
    carries them); they do not need to be threaded as a
    separate parameter.

    Cursor-based gating (ADR-074) is the canonical
    mechanism for "has anything changed since I last ran?".
    Systems that emit events of their own MUST distinguish
    their own outputs from external triggers via the
    World's ``last_event_*`` pointers or a dedicated
    component slot — not via a side-channel event list.

    Implementations should be PURE — no I/O, no side effects.
    If a system needs to talk to the outside world, emit an
    event (``call_external_api.requested``) that a SEPARATE
    adapter (an I/O system) consumes out-of-band and turns
    back into an event.

    The system MAY be ``async`` if the application prefers
    that style (it composes more easily with the dispatcher's
    async tick loop). A sync function is also acceptable.
    """

    def __call__(self, world: "World") -> SystemReturn: ...


# Backwards-compat aliases. New code should use ``WorldSystem``.
# ``ReactiveSystem`` and ``CyclicSystem`` are now interchangeable
# at the type level — both are ``(World) -> list[Event]``. The
# distinction (event-driven vs sweep) was an implementation
# detail of the old dispatcher; the new incremental dispatcher
# folds then runs all systems once per tick.
ReactiveSystem = WorldSystem
CyclicSystem = WorldSystem

# Type aliases for plain callables.
System = typing.Callable[["World"], SystemReturn]
Reactive = typing.Callable[["World"], SystemReturn]
Cyclic = typing.Callable[["World"], SystemReturn]

__all__ = [
    "Cyclic",
    "CyclicSystem",
    "Reactive",
    "ReactiveSystem",
    "System",
    "WorldSystem",
]
