# SPDX-FileCopyrightText: 2026 kinetgraph
#
# SPDX-License-Identifier: Apache-2.0

"""
Unit tests for ``LiteLLMToolWorker`` (ADR-043).

The worker is the canonical path going forward
(ADR-036 ``@tool_worker`` pattern orchestrated by
``WorkerManager``). The tests cover:

  - The schema generated by ``@tool_worker`` (the
    contract that the ``ToolRouter`` consumes to
    route the request).
  - The ``invoke`` return envelope (JSON-serialisable
    dict with ``text`` / ``model`` / ``usage`` /
    ``finish_reason`` / ``cost_usd`` / ``latency_ms``).
  - The timeout / error path: a transport timeout
    returns ``Err(TimeoutError(...))``; a transport
    error returns ``Err(...)``.

The transport is mocked (the worker is exercised
end-to-end with a fake ``LLMTransport``); no real
LLM call is made.
"""

from __future__ import annotations

import asyncio
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from kntgraph.agents.tools.llm import LiteLLMToolWorker


def test_litellm_worker_metadata():
    """The worker carries the ADR-043 contract: name
    is ``chat_llm`` (the wire-level identifier used
    by ``ToolRouter``)."""
    assert LiteLLMToolWorker.name == "chat_llm"
    assert LiteLLMToolWorker.description.startswith("Generic LLM completion")
    schema = LiteLLMToolWorker.input_schema
    # The schema exposes ``system`` and ``user`` as
    # required strings; ``model``, ``temperature``,
    # ``max_tokens`` are optional. These are the
    # kwargs the system passes when it emits
    # ``tool.chat_llm.requested``.
    props = schema["properties"]
    assert "system" in props
    assert "user" in props
    assert "model" in props
    assert "temperature" in props
    assert "max_tokens" in props
    assert "think" in props


def test_litellm_worker_is_registerable_in_worker_manager():
    """The worker satisfies the ``tool_worker`` marker:
    it has a ``name``, ``description``, and
    ``input_schema`` (set by the ``@tool_worker``
    decorator). The ``WorkerManager.register``
    accepts it as a class with these attributes.
    """
    assert LiteLLMToolWorker.name == "chat_llm"
    assert LiteLLMToolWorker.input_schema["type"] == "object"


def test_litellm_worker_init_loads_default_config():
    """``__init__`` reads the LLM config from the
    environment. With a fresh process and the test
    env (``LLMConfig.from_env``), the worker has a
    default model. The exact value depends on the
    test env (``FMH_LLM_DEFAULT_MODEL``); we just
    assert the worker constructed without error.
    """
    worker = LiteLLMToolWorker()
    assert worker._default_model is not None
    assert worker._timeout_s > 0


@pytest.mark.asyncio
async def test_invoke_returns_envelope_on_ok():
    """The worker translates the transport's dict
    into the public envelope (``text`` / ``model``
    / ``usage`` / ``finish_reason`` / ``cost_usd``
    / ``latency_ms``). The result is a JSON-
    serialisable dict (the result crosses the
    process boundary via the ``WorkerManager``'s
    ``_invoke_tool_sync``).
    """

    fake_completion: dict[str, Any] = {
        "choices": [
            {
                "message": {"content": "Olá! Eu sou a assistente."},
                "finish_reason": "stop",
            }
        ],
        "model": "ollama/qwen3.5:4b",
        "usage": {
            "prompt_tokens": 12,
            "completion_tokens": 8,
            "total_tokens": 20,
        },
    }
    fake_transport = AsyncMock(return_value=fake_completion)
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        r = await worker.invoke(
            system="You are a helpful assistant.",
            user="Olá!",
            idempotency_key="test-key-1",
        )
    assert r.is_ok()
    payload = r.unwrap()
    assert payload["text"] == "Olá! Eu sou a assistente."
    assert payload["model"] == "ollama/qwen3.5:4b"
    assert payload["finish_reason"] == "stop"
    assert payload["usage"] == {
        "prompt_tokens": 12,
        "completion_tokens": 8,
        "total_tokens": 20,
    }
    assert payload["latency_ms"] >= 0


@pytest.mark.asyncio
async def test_invoke_returns_err_on_transport_timeout():
    """A transport timeout returns ``Err(TimeoutError)``
    so the ``WorkerManager`` emits a
    ``tool.chat_llm.failed`` event with a clear
    error."""
    fake_transport = AsyncMock(side_effect=asyncio.TimeoutError("provider hung"))
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        worker._timeout_s = 0.1
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-2",
        )
    assert r.is_err()
    err = r.err_value()
    assert isinstance(err, TimeoutError)


@pytest.mark.asyncio
async def test_invoke_returns_err_on_generic_transport_error():
    """A non-timeout transport error returns
    ``Err(Exception)`` (the ``WorkerManager``
    propagates this to the agent's EventLog as a
    ``tool.chat_llm.failed`` event).
    """
    fake_transport = AsyncMock(side_effect=RuntimeError("provider down"))
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-3",
        )
    assert r.is_err()
    err = r.err_value()
    assert isinstance(err, RuntimeError)
    assert "provider down" in str(err)


@pytest.mark.asyncio
async def test_invoke_resolves_default_model_from_config():
    """When the system does not pass a model, the
    worker falls back to ``LLMConfig.default_model``.
    """

    fake_completion: dict[str, Any] = {
        "choices": [
            {
                "message": {"content": "ok"},
                "finish_reason": "stop",
            }
        ],
        "model": "default-model-from-config",
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }
    fake_transport = AsyncMock(return_value=fake_completion)
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        worker._default_model = "default-model-from-config"
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-4",
            # No ``model`` kwarg → default.
        )
    assert r.is_ok()
    # The transport receives the default model.
    call_kwargs = fake_transport.call_args.kwargs
    # ``fake_transport`` was called with the
    # ``LLMRequest``; we check that the request's
    # ``model`` matches the default.
    assert call_kwargs.get("model") is None or "default" in str(call_kwargs)
    # The result envelope carries the model that
    # the transport reported.
    assert r.unwrap()["model"] == "default-model-from-config"
