# SPDX-FileCopyrightText: 2026 kinetgraph
#
# SPDX-License-Identifier: Apache-2.0

"""
Unit tests for ``LiteLLMToolWorker`` (ADR-043).

The worker is the canonical path going forward
(ADR-036 ``@tool_worker`` pattern orchestrated by
``WorkerManager``). The tests cover:

  - The schema generated by ``@tool_worker`` (the
    contract that the ``ToolRouter`` consumes to
    route the request).
  - The ``invoke`` return envelope (JSON-serialisable
    dict with ``text`` / ``model`` / ``usage`` /
    ``finish_reason`` / ``cost_usd`` / ``latency_ms``).
  - The timeout / error path: a transport timeout
    returns ``Err(ToolError)`` (with the original
    ``TimeoutError`` as ``__cause__``); a transport
    error returns ``Err(ToolError)`` (with the
    original exception as ``__cause__``).

The transport is mocked (the worker is exercised
end-to-end with a fake ``LLMTransport``); no real
LLM call is made.
"""

from __future__ import annotations

import asyncio
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from kntgraph.agents.tools.llm import (
    LLMAuthError,
    LLMRateLimitError,
    LiteLLMToolWorker,
)
from kntgraph.core.result import ToolError


def test_litellm_worker_metadata():
    """The worker carries the ADR-043 contract: name
    is ``chat_llm`` (the wire-level identifier used
    by ``ToolRouter``)."""
    assert LiteLLMToolWorker.name == "chat_llm"
    assert LiteLLMToolWorker.description.startswith("Generic LLM completion")
    schema = LiteLLMToolWorker.input_schema
    # The schema exposes ``system`` and ``user`` as
    # required strings; ``model``, ``temperature``,
    # ``max_tokens`` are optional. These are the
    # kwargs the system passes when it emits
    # ``tool.chat_llm.requested``.
    props = schema["properties"]
    assert "system" in props
    assert "user" in props
    assert "model" in props
    assert "temperature" in props
    assert "max_tokens" in props
    assert "think" in props


def test_litellm_worker_is_registerable_in_worker_manager():
    """The worker satisfies the ``tool_worker`` marker:
    it has a ``name``, ``description``, and
    ``input_schema`` (set by the ``@tool_worker``
    decorator). The ``WorkerManager.register``
    accepts it as a class with these attributes.
    """
    assert LiteLLMToolWorker.name == "chat_llm"
    assert LiteLLMToolWorker.input_schema["type"] == "object"


def test_litellm_worker_init_loads_default_config():
    """``__init__`` reads the LLM config from the
    environment. With a fresh process and the test
    env (``LLMConfig.from_env``), the worker has a
    default model. The exact value depends on the
    test env (``KNT_LLM_DEFAULT_MODEL``); we just
    assert the worker constructed without error.
    """
    worker = LiteLLMToolWorker()
    assert worker._default_model is not None
    assert worker._timeout_s > 0


@pytest.mark.asyncio
async def test_invoke_returns_envelope_on_ok():
    """The worker translates the transport's dict
    into the public envelope (``text`` / ``model``
    / ``usage`` / ``finish_reason`` / ``cost_usd``
    / ``latency_ms``). The result is a JSON-
    serialisable dict (the result crosses the
    process boundary via the ``WorkerManager``'s
    ``_invoke_tool_sync``).
    """

    fake_completion: dict[str, Any] = {
        "choices": [
            {
                "message": {"content": "Olá! Eu sou a assistente."},
                "finish_reason": "stop",
            }
        ],
        "model": "ollama/qwen3.5:4b",
        "usage": {
            "prompt_tokens": 12,
            "completion_tokens": 8,
            "total_tokens": 20,
        },
    }
    fake_transport = AsyncMock(return_value=fake_completion)
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        r = await worker.invoke(
            system="You are a helpful assistant.",
            user="Olá!",
            idempotency_key="test-key-1",
        )
    assert r.is_ok()
    payload = r.unwrap()
    assert payload["text"] == "Olá! Eu sou a assistente."
    assert payload["model"] == "ollama/qwen3.5:4b"
    assert payload["finish_reason"] == "stop"
    assert payload["usage"] == {
        "prompt_tokens": 12,
        "completion_tokens": 8,
        "total_tokens": 20,
    }
    assert payload["latency_ms"] >= 0


@pytest.mark.asyncio
async def test_invoke_returns_err_on_transport_timeout():
    """A transport timeout returns ``Err(ToolError)``
    with the original ``TimeoutError`` preserved as
    ``__cause__`` (so the ``WorkerManager`` emits a
    ``tool.chat_llm.failed`` event with a clear
    error and the operator can introspect the
    cause)."""
    fake_transport = AsyncMock(side_effect=asyncio.TimeoutError("provider hung"))
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        worker._timeout_s = 0.1
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-2",
        )
    assert r.is_err()
    err = r.err_value()
    assert isinstance(err, ToolError)
    assert "llm_timeout" in str(err)
    assert isinstance(err.__cause__, TimeoutError)


@pytest.mark.asyncio
async def test_invoke_returns_err_on_generic_transport_error():
    """A non-timeout transport error returns
    ``Err(ToolError)`` (the ``WorkerManager``
    propagates this to the agent's EventLog as a
    ``tool.chat_llm.failed`` event). The original
    exception is preserved as ``__cause__``.
    """
    fake_transport = AsyncMock(side_effect=RuntimeError("provider down"))
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-3",
        )
    assert r.is_err()
    err = r.err_value()
    assert isinstance(err, ToolError)
    assert "llm_transport_error" in str(err)
    assert "provider down" in str(err)
    assert isinstance(err.__cause__, RuntimeError)


@pytest.mark.asyncio
async def test_invoke_resolves_default_model_from_config():
    """When the system does not pass a model, the
    worker falls back to ``LLMConfig.default_model``.
    """

    fake_completion: dict[str, Any] = {
        "choices": [
            {
                "message": {"content": "ok"},
                "finish_reason": "stop",
            }
        ],
        "model": "default-model-from-config",
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }
    fake_transport = AsyncMock(return_value=fake_completion)
    with patch(
        "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
        return_value=fake_transport,
    ):
        worker = LiteLLMToolWorker()
        worker._default_model = "default-model-from-config"
        r = await worker.invoke(
            system="sys",
            user="user",
            idempotency_key="test-key-4",
            # No ``model`` kwarg → default.
        )
    assert r.is_ok()
    # The transport receives the default model.
    call_kwargs = fake_transport.call_args.kwargs
    # ``fake_transport`` was called with the
    # ``LLMRequest``; we check that the request's
    # ``model`` matches the default.
    assert call_kwargs.get("model") is None or "default" in str(call_kwargs)
    # The result envelope carries the model that
    # the transport reported.
    assert r.unwrap()["model"] == "default-model-from-config"


class TestInvokeRetryPolicy:
    """
    ADR-061 §6.2 / §6.3: the worker retries on rate limit
    and timeout via ``with_timeout_and_retry`` (the
    framework-native counter comes from the toolkit —
    ``logger.warning("timeout.with_timeout_and_retry.
    attempt_n_of_max", ...)`` at timeout.py:322). The
    worker translates the final outcome into
    ``Result[dict, ToolError]``.

    The tests swap ``worker._retry_policy`` for a
    short-backoff variant so the retry loop returns in
    <100ms even when ``max_attempts=3`` fires. The
    production policy keeps ``base_delay=1.0,
    max_delay=10.0`` (the worker's ``__init__`` default).

    The transport is patched with an ``AsyncMock`` whose
    ``side_effect`` is a list of exceptions / values;
    ``AsyncMock`` consumes one entry per call so the
    iteration order is deterministic. The transport is
    patched at the worker level (the canonical seam per
    the file-level docstring).
    """

    def _patched_worker(
        self, transport_side_effect: list[Any]
    ) -> tuple[LiteLLMToolWorker, AsyncMock]:
        from kntgraph.resilience import BackoffPolicy

        fake_transport = AsyncMock(side_effect=transport_side_effect)
        patcher = patch(
            "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
            return_value=fake_transport,
        )
        patcher.start()
        worker = LiteLLMToolWorker()
        # Short backoff so the retry loop returns in <100ms
        # even when ``max_attempts=3`` fires. The production
        # policy stays in the worker's ``__init__``.
        worker._retry_policy = BackoffPolicy(
            max_attempts=3,
            base_delay=0.01,
            max_delay=0.05,
            retry_on=(LLMRateLimitError, asyncio.TimeoutError),
        )
        return worker, fake_transport

    @pytest.mark.asyncio
    async def test_rate_limit_retries_then_succeeds(self):
        """The transport raises ``LLMRateLimitError``
        on the first two attempts and returns a
        valid completion on the third. The worker
        retries via ``with_timeout_and_retry`` and
        the third call wins. ``AsyncMock`` records
        exactly three calls."""
        worker, fake_transport = self._patched_worker(
            [
                LLMRateLimitError("provider 429"),
                LLMRateLimitError("provider 429"),
                _ok_completion(text="hi"),
            ]
        )
        r = await worker.invoke(
            system="s",
            user="u",
            idempotency_key="rl-1",
        )
        assert r.is_ok()
        assert r.unwrap()["text"] == "hi"
        assert fake_transport.call_count == 3

    @pytest.mark.asyncio
    async def test_rate_limit_exhaustion_returns_err(self):
        """All three attempts hit ``LLMRateLimitError``.
        ``with_timeout_and_retry`` re-raises the last
        error; the worker translates it to
        ``Err(ToolError("llm_rate_limit: ..."))`` with
        the original ``LLMRateLimitError`` as
        ``__cause__`` (so the ``WorkerManager`` can
        surface a recognisable error in the
        ``tool.chat_llm.failed`` event)."""
        worker, fake_transport = self._patched_worker(
            [
                LLMRateLimitError("provider 429 a"),
                LLMRateLimitError("provider 429 b"),
                LLMRateLimitError("provider 429 c"),
            ]
        )
        r = await worker.invoke(
            system="s",
            user="u",
            idempotency_key="rl-exhaust",
        )
        assert r.is_err()
        err = r.err_value()
        assert isinstance(err, ToolError)
        assert "llm_rate_limit" in str(err)
        assert isinstance(err.__cause__, LLMRateLimitError)
        assert fake_transport.call_count == 3

    @pytest.mark.asyncio
    async def test_auth_error_does_not_retry(self):
        """``LLMAuthError`` is NOT in the
        ``retry_on`` tuple — credentials do not fix
        themselves on retry. The worker surfaces it
        on the first attempt (no second/third call)."""
        worker, fake_transport = self._patched_worker(
            [LLMAuthError("bad api key")]
        )
        r = await worker.invoke(
            system="s",
            user="u",
            idempotency_key="auth-1",
        )
        assert r.is_err()
        err = r.err_value()
        assert isinstance(err, ToolError)
        assert "llm_transport_error" in str(err)
        assert "bad api key" in str(err)
        assert isinstance(err.__cause__, LLMAuthError)
        assert fake_transport.call_count == 1

    @pytest.mark.asyncio
    async def test_timeout_retries_then_succeeds(self):
        """The transport raises
        ``asyncio.TimeoutError`` on the first attempt
        and returns a valid completion on the second.
        The ``BackoffPolicy`` retries on
        ``asyncio.TimeoutError`` (per-attempt timeout
        fires; the worker waits and retries)."""
        worker, fake_transport = self._patched_worker(
            [asyncio.TimeoutError(), _ok_completion(text="ok")]
        )
        r = await worker.invoke(
            system="s",
            user="u",
            idempotency_key="to-1",
        )
        assert r.is_ok()
        assert r.unwrap()["text"] == "ok"
        assert fake_transport.call_count == 2

    @pytest.mark.asyncio
    async def test_first_attempt_success_does_not_retry(self):
        """On success the worker does not invoke the
        transport again (the retry loop never
        enters). The envelope carries the transport's
        ``model`` (not the config default)."""
        worker, fake_transport = self._patched_worker(
            [_ok_completion(text="fast", model="openai/gpt-4o-mini")]
        )
        r = await worker.invoke(
            system="s",
            user="u",
            idempotency_key="ok-1",
            model="openai/gpt-4o-mini",
        )
        assert r.is_ok()
        assert r.unwrap()["text"] == "fast"
        assert fake_transport.call_count == 1

    @pytest.mark.asyncio
    async def test_caller_model_overrides_default_in_retry_loop(self):
        """When the caller passes a ``model=`` kwarg,
        every retry attempt uses that model (the
        ``BackoffPolicy`` does not change the request
        payload — only the call count). The
        transport sees the caller-specified model on
        every attempt."""
        from kntgraph.tools.llm_transport import LLMRequest

        attempts: list[str] = []

        async def fake_call(request: LLMRequest) -> dict:
            attempts.append(request.model)
            if len(attempts) < 2:
                raise LLMRateLimitError("429")
            return _ok_completion(text="ok", model=request.model)

        transport_mock = AsyncMock(side_effect=fake_call)
        with patch(
            "kntgraph.agents.tools.llm.LiteLLMTransportAdapter",
            return_value=transport_mock,
        ):
            worker = LiteLLMToolWorker()
            worker._timeout_s = 5.0
            from kntgraph.resilience import BackoffPolicy

            worker._retry_policy = BackoffPolicy(
                max_attempts=3,
                base_delay=0.01,
                max_delay=0.05,
                retry_on=(LLMRateLimitError, asyncio.TimeoutError),
            )
            r = await worker.invoke(
                system="s",
                user="u",
                idempotency_key="caller-1",
                model="anthropic/claude-3-5-sonnet",
            )
        assert r.is_ok()
        assert attempts == [
            "anthropic/claude-3-5-sonnet",
            "anthropic/claude-3-5-sonnet",
        ]


def _ok_completion(
    *, text: str = "ok", model: str = "fake/model"
) -> dict[str, Any]:
    """Helper: a transport-shaped completion dict
    that the worker can parse into the public
    envelope."""
    return {
        "choices": [
            {
                "message": {"content": text},
                "finish_reason": "stop",
            }
        ],
        "model": model,
        "usage": {
            "prompt_tokens": 1,
            "completion_tokens": 1,
            "total_tokens": 2,
        },
    }
