# SPDX-FileCopyrightText: 2026 kinetgraph
#
# SPDX-License-Identifier: Apache-2.0
"""
Tests for the README version badge (ADR-051).

The badge is generated by ``scripts/readme_stats.py``
from ``kntgraph.__version__`` (which itself is
derived from the git tag by ``setuptools_scm``). The
test exercises the ``_version_badge()`` helper end
to end: it imports ``kntgraph`` to get the version
and asserts the rendered badge follows the
``![Version](https://img.shields.io/badge/version-...)``
format.

The test runs in any environment (CI, local
checkout) and asserts the contract.
"""

from __future__ import annotations


import pytest

from scripts.readme_stats import _version_badge


class TestVersionBadge:
    """The README version badge is a markdown image
    whose alt text is ``Version`` and whose
    ``badge/version-`` URL fragment matches
    ``kntgraph.__version__``.
    """

    def test_badge_format(self) -> None:
        """The badge follows the
        ``![Version](https://img.shields.io/badge/version-X.Y.Z-blue)``
        format, with the version being the
        ``kntgraph.__version__`` (stripped of any
        local / dev suffix so the badge always
        shows a clean ``X.Y.Z``).
        """
        badge = _version_badge()
        # The badge starts with the standard
        # markdown image syntax.
        assert badge.startswith("![")
        assert "](https://img.shields.io/badge/version-" in badge

    def test_badge_contains_clean_version(self) -> None:
        """The badge carries the **base semver triple**
        of the latest git tag (no ``devN+g<sha>``
        suffix). The badge is what the user sees;
        a ``0.10.1.dev0+gc0adc4211`` would be
        confusing on the README.

        Note: the contract is "the badge shows the
        latest released version", not "the badge
        shows ``__version__``'s base". When the
        working tree is dirty (e.g. mid-edit), the
        ``setuptools_scm`` ``__version__`` infers
        the next minor/patch (``0.10.1.dev0+g...``)
        to signal "not the tagged release"; the
        badge instead reflects the **tag** so the
        README does not flip to ``0.10.1`` mid-edit.
        The tag-derived version is the canonical
        release identifier; the dirty-tree infix is
        a transient artefact.
        """
        import subprocess

        from packaging.version import Version

        # Derive the latest tag the same way the
        # badge script does.
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            pytest.skip("no reachable tag from HEAD; cannot exercise the contract")
        tag = result.stdout.strip().lstrip("v")
        expected = Version(tag).base_version
        badge = _version_badge()
        assert expected in badge, (
            f"expected the tag base version {expected!r} in the badge; got: {badge!r}"
        )
        # The dev / local suffix should NOT be in
        # the badge.
        assert "+g" not in badge, (
            f"badge must not carry the local '+g<sha>' suffix; got: {badge!r}"
        )
        assert ".dev" not in badge, (
            f"badge must not carry the '.devN' pre-release suffix; got: {badge!r}"
        )
